wip

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -16,72 +16,60 @@ set -e
 ## Source debconf library.
 . /usr/share/debconf/confmodule
 
-## Get the name of the package
-PACKAGE="${DPKG_MAINTSCRIPT_PACKAGE}"
-DMVERSION='@@VERSION@@'
-echo "Running $1 ${PACKAGE} version ${DMVERSION}."
-
-## Is this the headless package?
-HEADLESS_PACKAGE="$( echo "${PACKAGE}" | grep 'headless' )" || true
-
-## Is this a desktop system?
-SOCKET_STATUS="$( netstat -lp 2>/dev/null | grep -E 'Xorg|Xwayland' | grep 'X11' )" || true
-PROCESS_STATUS="$( pgrep 'Xorg|Xwayland' )" || true
-
-echo "HEADLESS_PACKAGE=${HEADLESS_PACKAGE}"
-echo "SOCKET_STATUS=${SOCKET_STATUS}"
-echo "PROCESS_STATUS=${PROCESS_STATUS}"
-
-## Check system and ask user
-# if [ -z "${SOCKET_STATUS}" ] && [ -z "${PROCESS_STATUS}" ] && [ -z "${HEADLESS_PACKAGE}" ]; then
-if [ -n "${SOCKET_STATUS}" ] && [ -n "${PROCESS_STATUS}" ] && [ -z "${HEADLESS_PACKAGE}" ]; then
-    ## prompt headless warning
-    db_input high dmx/headless_warning || true
-    db_input high dmx/continue_installation || true
-    db_go
-    db_get dmx/continue_installation
-    echo "<$RET>"
-    if [ "$RET" != "true" ]; then
-        ## Remove the changes from the db.
-        echo "Aborting $1."
-        db_purge
-        ## Abort installation
-        ## IMPORTANT: exit 0 will not cancel the installation process,
-        ## but only exit from preinst and continue with installation.
-        exit 1
-    fi
-fi
-
-
-###  FIXME
-###  Backing up the db depends on the location of the db, which is a config parameter in config properties.
-###  So in the funture we have to read that!
-DBDIR='/var/lib/dmx/dmx-db'
-BACKUPDATE="$( date +%F-%H:%M:%S )"
-
-## was there a previously installed DMX
-INSTALLED_VERSION="$( dpkg -s ${PACKAGE} 2>/dev/null | sed -n 's/^Version: //p' | cut -d'~' -f1 )"
-PREVIOUSDBVERSION="$( if [ -d ${DBDIR} ]; then find ${DBDIR} -name ".dm-version.*" | cut -d'.' -f'3-' | sort -V | tail -n1; fi )"
-
-
-if [ -n "${PREVIOUSDBVERSION}" ]; then
-    echo "Found previous db-version ${PREVIOUSDBVERSION}."
-fi
-
-## check if dmx is already running and stop it then
-systemctl is-active --quiet dmx.service && deb-systemd-invoke stop dmx
-
 case "$1" in
-    install)
-    id -u dmx >/dev/null 2>&1 || useradd --system --user-group --home-dir '/var/lib/dmx' --shell '/bin/false' --comment 'DMX - The Context Machine' dmx
-    if [ ! -d /var/lib/dmx ]; then
-	mkdir /var/lib/dmx
-	#chown dmx:dmx /var/lib/dmx
+    install|upgrade)
+    ## Get the name of the package
+    PACKAGE="${DPKG_MAINTSCRIPT_PACKAGE}"
+    DMVERSION='@@VERSION@@'
+    echo "Running $1 ${PACKAGE} version ${DMVERSION}."
+
+    ## Is this the headless package?
+    HEADLESS_PACKAGE="$( echo "${PACKAGE}" | grep 'headless' )" || true
+
+    ## Is this a desktop system?
+    SOCKET_STATUS="$( netstat -lp 2>/dev/null | grep -E 'Xorg|Xwayland' | grep 'X11' )" || true
+    PROCESS_STATUS="$( pgrep 'Xorg|Xwayland' )" || true
+
+    echo "HEADLESS_PACKAGE=${HEADLESS_PACKAGE}"
+    echo "SOCKET_STATUS=${SOCKET_STATUS}"
+    echo "PROCESS_STATUS=${PROCESS_STATUS}"
+
+    ## Check system and ask user
+    # if [ -z "${SOCKET_STATUS}" ] && [ -z "${PROCESS_STATUS}" ] && [ -z "${HEADLESS_PACKAGE}" ]; then
+    if [ -n "${SOCKET_STATUS}" ] && [ -n "${PROCESS_STATUS}" ] && [ -z "${HEADLESS_PACKAGE}" ]; then
+	## prompt headless warning
+	db_input high dmx/headless_warning || true
+	db_input high dmx/continue_installation || true
+	db_go
+	db_get dmx/continue_installation
+	echo "continue_installation=<$RET>"
+	if [ "$RET" != "true" ]; then
+    	    ## Remove the changes from the db.
+    	    echo "Aborting $1."
+    	    db_purge
+    	    ## Abort installation
+    	    ## IMPORTANT: exit 0 will not cancel the installation process,
+    	    ## but only exit from preinst and continue with installation.
+    	    exit 1
+	fi
     fi
+
+    ###  FIXME
+    ###  Backing up the db depends on the location of the db, which is a config parameter in config properties.
+    ###  So in the funture we have to read that!
+    DBDIR='/var/lib/dmx/dmx-db'
+    BACKUPDATE="$( date +%F-%H:%M:%S )"
+    ## check if dmx is already running and stop it then
+    systemctl is-active --quiet dmx.service && deb-systemd-invoke stop dmx
+    ## was there a previously installed DMX
+    INSTALLED_VERSION="$( dpkg -s ${PACKAGE} 2>/dev/null | sed -n 's/^Version: //p' | cut -d'~' -f1 )"
+    PREVIOUSDBVERSION="$( if [ -d ${DBDIR} ]; then find ${DBDIR} -name ".dm-version.*" | cut -d'.' -f'3-' | sort -V | tail -n1; fi )"
     ## backup existing database
     if [ -d ${DBDIR} ]; then
         if [ -n "${PREVIOUSDBVERSION}" ]; then
             BACKUPDIR="${DBDIR}-${PREVIOUSDBVERSION}-backup-$BACKUPDATE"
+        elif [ -n "${INSTALLED_VERSION}" ]; then
+            BACKUPDIR="${DBDIR}-${INSTALLEDDBVERSION}-backup-$BACKUPDATE"
         else
             BACKUPDIR="${DBDIR}-preinst_${DMVERSION}-backup-$BACKUPDATE"
         fi
@@ -93,26 +81,10 @@ case "$1" in
     # chown dmx:dmx ${DBDIR}
     chmod 750 ${DBDIR}
     touch ${DBDIR}/.dm-version.$DMVERSION
-    if [ -d /etc/dmx ]; then
-	    # chown root:dmx /etc/dmx
-	    chmod 750 /etc/dmx
-    fi
-    ;;
-
-    upgrade)
-    ## backup existing database
-    if [ -d ${DBDIR} ]; then
-        if [ -n "${PREVIOUSDBVERSION}" ]; then
-            BACKUPDIR="${DBDIR}-${PREVIOUSDBVERSION}-backup-$BACKUPDATE"
-        elif [ -n "${INSTALLED_VERSION}" ]; then
-            BACKUPDIR="${DBDIR}-${INSTALLEDDBVERSION}-backup-$BACKUPDATE"
-        else
-            BACKUPDIR="${DBDIR}-preinst_${DMVERSION}-backup-$BACKUPDATE"
-        fi
-        cp -a ${DBDIR} ${BACKUPDIR}
-        echo "Your existing database has been backed-up (copied) to ${BACKUPDIR}."
-        touch ${DBDIR}/.dm-version.$DMVERSION
-    fi
+#    if [ -d /etc/dmx ]; then
+#	    # chown root:dmx /etc/dmx
+#	    chmod 750 /etc/dmx
+#    fi
     ;;
 
     abort-upgrade)
